apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: managed-pipeline
  namespace: managed-release1053
spec:
  applications:
    - demo
  origin: dev-release1053
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/johnbieren/jb-konflux-demos.git"
        - name: revision
          value: main
        - name: pathInRepo
          value: "release_1109/managed-dummy.yaml"
    serviceAccountName: release-service-account
  policy: mvp-policy
