---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'false'
    version: v2
  name: tenant-pipeline1
spec:
  target: managed-ns2
  application: demo
  tenantPipeline:
    serviceAccountName: appstudio-pipeline
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/Paul123111/community-catalog.git
        - name: revision
          value: staging
        - name: pathInRepo
          value: pipelines/hello-tenant-pipeline/hello-tenant-pipeline.yaml
    params:
      - name: name
        value: "paul"
  # tenantPipeline:
  #   serviceAccountName: appstudio-pipeline
  #   pipelineRef:
  #     resolver: git
  #     params:
  #       - name: url
  #         value: https://github.com/Paul123111/community-catalog.git
  #       - name: revision
  #         value: development
  #       - name: pathInRepo
  #         value: pipelines/quay-pipeline/quay-pipeline.yaml
  #   params:
  #     - name: snapshotPath
  #       value: snapshot.json
  #     - name: snapshotJson
  #       value: |
  #         {
  #           "application": "demo",
  #           "artifacts": {},
  #           "components": [
  #             {
  #               "containerImage": "quay.io/hacbs-release-tests/user-ns2-team-tenant/simple-python/devfile-sample-python-basic@sha256:199c12573aeec5a0761b4ebcd9769291dd4b94cc9ff15980c64d98e8a03d2dce",
  #               "repository": "quay.io/pafitzge-konflux/testimages",
  #               "name": "devfile-sample-python-basic",
  #               "source": {
  #                 "git": {
  #                   "revision": "fc2d04d48ee9c2a83d268c17a1504f28483b2177",
  #                   "url": "https://github.com/scoheb/devfile-sample-python-basic"
  #                 }
  #               },
  #               "tags": [
  #                 "testtag"
  #               ]
  #             },
  #             {
  #               "containerImage": "quay.io/hacbs-release-tests/user-ns2-team-tenant/simple-python/devfile-sample-python-basic@sha256:199c12573aeec5a0761b4ebcd9769291dd4b94cc9ff15980c64d98e8a03d2dce",
  #               "repository": "quay.io/pafitzge-konflux/testimages",
  #               "name": "devfile-sample-python-advanced",
  #               "source": {
  #                 "git": {
  #                   "revision": "fc2d04d48ee9c2a83d268c17a1504f28483b2177",
  #                   "url": "https://github.com/scoheb/devfile-sample-python-basic"
  #                 }
  #               },
  #               "tags": [
  #                 "testtag"
  #               ]
  #             }
  #           ]
  #         }
  finalPipeline:
    serviceAccountName: appstudio-pipeline
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/Paul123111/community-catalog.git
        - name: revision
          value: fixing-slack-task
        - name: pathInRepo
          value: pipelines/notify-slack-on-failure-sample/notify-slack-on-failure-sample.yaml
    params:
      # - name: message
      #   value: "{'text': 'hello :@@CIRCLE_TYPE@@:'}"
      - name: secretName
        value: slack-secret
      - name: secretKeyName
        value: webhook
